### ISSUE TITLE
Update status when network is changed via Apple Menu

### ISSUE THREAD

**Issue by Josch-** [yusukeshibata/netloc#5]
Hi,

maybe this is the same as your enhancement issue "observe changes from network preference" - when I change the location via the Apple Menu the netloc status in the menu bar does not change to the actual location setting.

Hope that will be fixed soon :-)

Thanks a lot in advance and regards from Germany,

Josch

**Comment by yusukeshib** [comment]
Thank you for your proposal.
I implemented that with last commit.
Please check it from [here](/yusukeshibata/netloc/blob/master/dist/netloc.zip?raw=true), or
`brew cask uninstall netloc && brew cask install netloc`

**Comment by yusukeshib** [comment]
fixed.

**Comment by Josch-** [comment]
Excellent - works perfect. A big thank you! :-)
