### ISSUE TITLE
Network locations sort order

### ISSUE THREAD

**Issue by Josch-** [yusukeshibata/netloc#6]
Hi,

my wish is an alphabetical sort order of the displayed network locations 
in the netloc menu. That would give that menu much more clarity :-)

Thanks a lot in advance and regards from Germany,

Josch

**Comment by yusukeshib** [comment]
done

**Comment by yusukeshib** [comment]
Hi, @Josch-, fixed. check please.

`brew cask uninstall netloc && brew cask install netloc`

**Comment by Josch-** [comment]
Hi,

that's incredibly fast :-O

But one problem - I had no brew on my machine and installed it, went through "brew cask uninstall netloc && brew cask install netloc" that said that there is no installation of netloc. So I did a "brew cask install netloc" and netloc was installed. But I can't find it? Where is it installed?

Thanks a lot in advance.

Best wishes,

Josch

**Comment by Josch-** [comment]
OK, found it - works flawlessly :-)
