### ISSUE TITLE
linked binary not working macOS High Sierra

### ISSUE THREAD

**Issue by helptiger** [yusukeshibata/netloc#7]
![screenshot 2018-05-02 at 08 28 11 am](https://user-images.githubusercontent.com/10258902/39508440-ccf44548-4de2-11e8-9a44-46e5e98cba12.png)

**Comment by yusukeshib** [comment]
@helptiger Sorry for inconvenience, and thanks for reporting.
Fixed with signing the app.

Retry please!

**Comment by helptiger** [comment]
working great now! thanks
